name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Staging
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "asset-mgmt-staging"
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    # Only deploy to production if staging succeeds
    if: github.ref == 'refs/heads/main'
    # Require manual approval
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "asset-mgmt-production"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
